"""
Model Explainability and Feature Importance Module
==================================================
Extracts split and gain importance from the production LightGBM pipeline
to interpret the primary drivers of pre-dispatch delivery dissatisfaction.
"""

import os
import sys
import joblib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Resolve root directory for modular imports
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)


def generate_feature_importance_report():
    """
    Loads saved pipeline, dynamically resolves feature names directly from
    fitted transformers, and saves the top feature importance plot.
    """
    model_path = os.path.join(PROJECT_ROOT, "models", "lgbm_dissatisfaction_pipeline.pkl")
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model artifact not found at: {model_path}")

    print("[1/3] Loading saved production pipeline artifact...")
    pipeline = joblib.load(model_path)

    # Dynamically extract preprocessor (first step) and model (last step)
    preprocessor = pipeline.steps[0][1]
    classifier = pipeline.steps[-1][1]

    print("[2/3] Extracting dynamic feature names from pipeline...")
    # Extract exact transformed feature names directly from fitted preprocessor
    try:
        feature_names = preprocessor.get_feature_names_out()
        # Clean up column prefixes generated by ColumnTransformer (e.g. 'num__', 'cat__')
        clean_feature_names = [
            f.replace("num__", "").replace("cat__", "").replace("remainder__", "")
            for f in feature_names
        ]
    except Exception:
        # Fallback if get_feature_names_out fails
        num_features = len(classifier.feature_importances_)
        clean_feature_names = [f"feature_{i}" for i in range(num_features)]

    importances = classifier.feature_importances_

    # Verify length match before creating DataFrame
    if len(clean_feature_names) != len(importances):
        min_len = min(len(clean_feature_names), len(importances))
        clean_feature_names = clean_feature_names[:min_len]
        importances = importances[:min_len]

    feat_df = pd.DataFrame({
        "Feature": clean_feature_names,
        "Importance": importances
    }).sort_values(by="Importance", ascending=False)

    print("[3/3] Generating feature importance visualization...")
    plt.figure(figsize=(10, 6))
    sns.barplot(
        data=feat_df.head(12),
        x="Importance",
        y="Feature",
        palette="rocket"
    )
    plt.title("Top 12 Operational Drivers of Order Dissatisfaction (LightGBM)", fontsize=13, pad=15)
    plt.xlabel("Feature Importance (Split Score)", fontsize=11)
    plt.ylabel("Operational Predictor", fontsize=11)
    plt.tight_layout()

    # Save figure to reports/figures/
    output_dir = os.path.join(PROJECT_ROOT, "reports", "figures")
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "satisfaction_feature_importance.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    print(f"[SUCCESS] Feature importance plot saved to: {output_path}")


if __name__ == "__main__":
    generate_feature_importance_report()